# Replace 'ae-boilerplate' with your application name
application: afgs
version: 1
runtime: python
api_version: 1

default_expiration: "0d"

#builtins:
#- datastore_admin: on
#- remote_api: on

handlers:

- url: /favicon\.ico
  mime_type: image/png
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /img/(.*\.(gif|png|jpg))
  static_files: static/img/\1
  upload: static/img/(.*\.(gif|png|jpg))
  
- url: /swf/(.*\.swf)
  static_files: static/swf/\1
  upload: static/swf/(.*\.swf)

- url: /css/(.*\.css)
  mime_type: text/css
  static_files: static/css/\1
  upload: static/css/(.*\.css)

- url: /js/(.*\.js)
  mime_type: text/javascript
  static_files: static/js/\1
  upload: static/js/(.*\.js)

- url: .*
  static_files: static/index.html
  upload: static/index.html
